export function formatResultsAsText(results: {
  urgency_tier: string
  risk_score: number
  confidence: string
  recommendation: string
  probabilities: { benign: number; malignant: number }
  condition_estimate?: string
}): string {
  const date = new Date().toLocaleString()

  return `
SkinTag Analysis Report
Generated: ${date}

RISK ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Risk Level: ${results.urgency_tier.toUpperCase()}
Risk Score: ${Math.round(results.risk_score * 100)}%
Confidence: ${results.confidence}

RECOMMENDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${results.recommendation}

CLASSIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Benign: ${Math.round(results.probabilities.benign * 100)}%
Malignant: ${Math.round(results.probabilities.malignant * 100)}%
${results.condition_estimate ? `\nMost Likely: ${results.condition_estimate}` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DISCLAIMER: This tool is for educational purposes only
and should not replace professional medical advice.
Always consult a healthcare provider for skin concerns.

Generated by SkinTag (https://github.com/skintaglabs/main)
`.trim()
}
