import html2canvas from 'html2canvas'

export async function downloadResultsAsImage(elementId: string): Promise<void> {
  const element = document.getElementById(elementId)
  if (!element) {
    throw new Error('Results element not found')
  }

  const canvas = await html2canvas(element, {
    backgroundColor: '#f6f4f0',
    scale: 2,
    logging: false,
    useCORS: true,
    allowTaint: true,
    onclone: (clonedDoc) => {
      // Add fallback CSS to override oklch colors
      const style = clonedDoc.createElement('style')
      style.textContent = `
        * {
          --color-text: #1a1a1a !important;
          --color-text-muted: #666666 !important;
          --color-surface: #ffffff !important;
          --color-border: #e5e5e5 !important;
          --color-accent-warm: #ea580c !important;
          --color-accent-cool: #0891b2 !important;
        }
      `
      clonedDoc.head.appendChild(style)
    }
  })

  const blob = await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) {
        resolve(blob)
      } else {
        reject(new Error('Failed to create blob from canvas'))
      }
    }, 'image/png')
  })

  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  const timestamp = new Date().toISOString().split('T')[0]
  link.download = `skintag-analysis-${timestamp}.png`
  link.href = url
  link.click()
  URL.revokeObjectURL(url)
}

export function copyResultsToClipboard(text: string): void {
  navigator.clipboard.writeText(text)
}

export function formatResultsAsText(results: {
  urgency_tier: string
  risk_score: number
  confidence: string
  recommendation: string
  probabilities: { benign: number; malignant: number }
  condition_estimate?: string
}): string {
  const date = new Date().toLocaleString()

  return `
SkinTag Analysis Report
Generated: ${date}

RISK ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Risk Level: ${results.urgency_tier.toUpperCase()}
Risk Score: ${Math.round(results.risk_score * 100)}%
Confidence: ${results.confidence}

RECOMMENDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${results.recommendation}

CLASSIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Benign: ${Math.round(results.probabilities.benign * 100)}%
Malignant: ${Math.round(results.probabilities.malignant * 100)}%
${results.condition_estimate ? `\nMost Likely: ${results.condition_estimate}` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DISCLAIMER: This tool is for educational purposes only
and should not replace professional medical advice.
Always consult a healthcare provider for skin concerns.

Generated by SkinTag (https://github.com/skintaglabs/main)
`.trim()
}
